//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 数据采集档案管理系统___课题版.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("数据采集档案管理系统___课题版.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _lock {
            get {
                object obj = ResourceManager.GetObject("_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		.ipt1{
        ///			border: none;
        ///			border-bottom: 1px solid black;
        ///			text-align: center;
        ///			width: 50mm;
        ///		}
        ///		.ipt2{
        ///			border: none;
        ///		}
        ///        thead td{
        ///            text-align: center;
        ///            padding: 7px 0px;
        ///        }
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;text-align: center; font-size: 14px;&quot;&gt;
        ///	&lt;div&gt;&lt;h1&gt;卷内备考表&lt;/h1&gt;&lt;/div&gt;
        ///    &lt;p style=&quot;text-align: left&quot;&gt;档号：&lt;span id=&quot;dh&quot;&gt;&lt;/span&gt;&lt;/p&gt;
        ///	&lt;div style=&quot;border: 1px solid blac [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string bkb {
            get {
                return ResourceManager.GetString("bkb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap doc {
            get {
                object obj = ResourceManager.GetObject("doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 					课题档案填报系统填写说明
        ///一、系统功能简介
        ///	课题档案填报系统是面向承担重大专项的项目（课题）组，用以收集项目（课题）及其档案信息，以项目（课题）组为单位进行填报。一个账户只能对应一个项目（课题）。
        ///	本系统主要实现项目（课题）、文件及档案信息填写、档案归档移交、查询统计及数据备份等功能。
        ///	项目（课题）下设课题（子课题）层级的，由项目（课题）承担单位将本项目（课题）基本信息填写完整，并将下设课题（子课题）用户设置（用户设置在后台管理模块）完成后，下发给课题（子课题）组，课题（子课题）组将本课题（子课题）内容填写完成后，导出光盘，将光盘送至项目（课题）组，项目（课题）组将信息审核、汇总后，导出光盘，统一报送给本专项办或专业机构。
        ///
        ///二、主要功能介绍
        ///	1）数据导入：用于收集结构化的数据（子课题层级提交的数据）及电子文件等。
        ///	2）录入加工：用于项目（课题）基本信息、文件及档案信息的填写、档案清单的导出等。
        ///	3）归档移交：用于数据导出。
        ///	4）查询统计：实现从不同角度对项目（课题）及文件等信息的查询与统计。
        ///	5）后台管理：主要是针对用户、字典、编码及电子全文路径进行管理。
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string explain {
            get {
                return ResourceManager.GetString("explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap file2 {
            get {
                object obj = ResourceManager.GetObject("file2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;
        ///      xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        ///      xmlns:w=&quot;urn:schemas-microsoft-com:office:word&quot;
        ///      xmlns:m=&quot;http://schemas.microsoft.com/office/2004/12/omml&quot;
        ///      xmlns=&quot;http://www.w3.org/TR/REC-html40&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=EmulateIE8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=gb2312&quot; /&gt;
        ///    &lt;meta name=&quot;ProgId&quot; content=&quot;Word.Document&quot; /&gt;
        ///    &lt;meta name=&quot;Generator&quot; content=&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string fm {
            get {
                return ResourceManager.GetString("fm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;
        ///      xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        ///      xmlns:w=&quot;urn:schemas-microsoft-com:office:word&quot;
        ///      xmlns:m=&quot;http://schemas.microsoft.com/office/2004/12/omml&quot;
        ///      xmlns=&quot;http://www.w3.org/TR/REC-html40&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=EmulateIE8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=gb2312&quot; /&gt;
        ///    &lt;meta name=&quot;ProgId&quot; content=&quot;Word.Document&quot; /&gt;
        ///    &lt;meta name=&quot;Generator&quot; content=&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string fm2 {
            get {
                return ResourceManager.GetString("fm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///&lt;html&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;style&gt;
        ///        thead td {
        ///            text-align: center;
        ///            padding: 7px 0px;
        ///        }
        ///		tbody td {
        ///			border: 1px solid black;
        ///			text-align: center;
        ///		}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1
        ///		style=&quot;word-break: break-all; text-align: center;; font-family: 黑体;&quot;&gt;卷内目录&lt;/h1&gt;
        ///	&lt;br /&gt;
        ///	&lt;br /&gt;
        ///	&lt;p style=&quot;word-break: break-all; font-family: 黑体; margin:13px 5px;&quot;&gt;
        ///		&lt;b&gt;档号:&lt;/b&gt;&lt;span id=&quot;ajbh&quot;&gt;&lt;/span&gt;
        ///		&lt;spa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string jnml {
            get {
                return ResourceManager.GetString("jnml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap login_1 {
            get {
                object obj = ResourceManager.GetObject("login_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Mbg {
            get {
                object obj = ResourceManager.GetObject("Mbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap message {
            get {
                object obj = ResourceManager.GetObject("message", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pdf {
            get {
                object obj = ResourceManager.GetObject("pdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_0010 {
            get {
                object obj = ResourceManager.GetObject("png_0010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_0098 {
            get {
                object obj = ResourceManager.GetObject("png_0098", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_0152 {
            get {
                object obj = ResourceManager.GetObject("png_0152", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_0217 {
            get {
                object obj = ResourceManager.GetObject("png_0217", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_0222 {
            get {
                object obj = ResourceManager.GetObject("png_0222", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_0228 {
            get {
                object obj = ResourceManager.GetObject("png_0228", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_0281 {
            get {
                object obj = ResourceManager.GetObject("png_0281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_0285 {
            get {
                object obj = ResourceManager.GetObject("png_0285", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_0289 {
            get {
                object obj = ResourceManager.GetObject("png_0289", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_1165 {
            get {
                object obj = ResourceManager.GetObject("png_1165", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_1644 {
            get {
                object obj = ResourceManager.GetObject("png_1644", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_1753 {
            get {
                object obj = ResourceManager.GetObject("png_1753", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap rar {
            get {
                object obj = ResourceManager.GetObject("rar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] System_Data_SQLite {
            get {
                object obj = ResourceManager.GetObject("System_Data_SQLite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap wait {
            get {
                object obj = ResourceManager.GetObject("wait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap xsl {
            get {
                object obj = ResourceManager.GetObject("xsl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap zhuxiao {
            get {
                object obj = ResourceManager.GetObject("zhuxiao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
